#### pod ####
replicaCount: 1
maxUnavailable: 0
maxSurge: 1

# namespace: $CI_PROJECT_NAMESPACE-$CI_COMMIT_REF_NAME
namespace: $NAME_PROJECT-$CI_COMMIT_REF_NAME

image: $REGISTRY_IMAGE_TAG
# imagePullSecrets: $CI_PROJECT_NAMESPACE-harbor-robot
imagePullSecrets: $CI_PROJECT_NAMESPACE-harbor-robot
imagePullPolicy: IfNotPresent

containerPort: 3000

livenessProbe: {}
#  failureThreshold: 3
#  httpGet:
#    path: /
#    port: 80
#  periodSeconds: 20
#  successThreshold: 1
#  timeoutSeconds: 5
#  initialDelaySeconds: 10

readinessProbe: {}
#  failureThreshold: 3
#  httpGet:
#    path: /
#    port: 80
#  periodSeconds: 10
#  successThreshold: 1
#  timeoutSeconds: 2

resources:
  limits:
    cpu: 2
    memory: 1Gi
  requests:
    cpu: 100m
    memory: 256Mi

#### autoscaling #####
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 8
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

#### service #####
service:
  type: LoadBalancer #(ClusterIP/LoadBalancer/NodePort)
  loadBalancerIP: 192.168.0.135
  port: 3000
  targetPort: 3000
  protocol: TCP

#### ingress #####
ingress:
  enabled: true
  annotations: {}
  #    nginx.ingress.kubernetes.io/rewrite-target: /$2
  #    nginx.ingress.kubernetes.io/auth-realm: realm string
  host: $DOMAIN_NAME
  path: /api(/|$)(.*)
  pathType: Prefix
  portNumber: 3000

migrate:
  enabled: true
  command:
    - yarn
  args:
    - migrate
