#### pod ####
# Work only if HPA is disabled
replicaCount: 1
maxUnavailable: 0
maxSurge: 1

namespace: $NAME_PROJECT-$CI_COMMIT_REF_NAME

image: $REGISTRY_IMAGE_TAG
imagePullSecrets: $NAME_PROJECT-harbor-robot
imagePullPolicy: IfNotPresent

containerPort: 3000

livenessProbe:
  failureThreshold: 3
  httpGet:
    path: /health
    port: 3000
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 5

readinessProbe:
  failureThreshold: 3
  httpGet:
    path: /health
    port: 3000
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 2

startupProbe:
  failureThreshold: 24
  httpGet:
    path: /health
    port: 3000
  periodSeconds: 5
  successThreshold: 1
  timeoutSeconds: 2

resources:
  limits:
    cpu: 2
    memory: 1Gi
  requests:
    cpu: 100m
    memory: 256Mi

#### autoscaling #####
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 8
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

#### service #####
service:
  type: ClusterIP #(ClusterIP/LoadBalancer/NodePort)
  loadBalancerIP: 192.168.0.135
  port: 3000
  targetPort: 3000
  protocol: TCP

#### ingress #####
ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  #    nginx.ingress.kubernetes.io/auth-realm: realm string
  host: $DOMAIN_NAME
  path: /api(/|$)(.*)
  pathType: Prefix
  portNumber: 3000

migrate:
  enabled: false
  command:
    - yarn
  args:
    - migrate
