FROM composer:2.1.9 as vendor
WORKDIR app
COPY . .
RUN composer install \
    --ignore-platform-reqs \
    --no-interaction \
    --no-plugins \
    --no-scripts \
    --prefer-dist


FROM harbor.smw.team/server-base/supervisord:php8.1

ARG STAGE=develop
WORKDIR /var/www/html
COPY --from=vendor /app/* .

RUN cp .deploy/$STAGE/daemon.conf    /etc/supervisor/conf.d/ && \
    cp .deploy/$STAGE/.env . && \
    chmod -R 777 /var/www/html/storage && \
    chmod -R 777 /var/www/html/bootstrap && \
    rm -rf .deploy .git
